### ISSUE TITLE
Resubmission procedure and versioning - should work before a new Data call

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/biodiversity-portal#10]
Facilitate full-dataset resubmissions: create respective data checks; facilitate the ‘assessment data snapshots’

**Comment by neil-ices-dk** [comment]
@IanMitchell1 to clarify at (or before) the 13th November meeting, the process envisaged as suggested by Lena in pre-call; (need to define a key (year, institute, datatype - B1, B3, survey?) for the data accession

**Comment by neil-ices-dk** [comment]
key confirmed as **year, institute, datatype - B1[Count Flag], B3, surveyID**
