### ISSUE TITLE
Data access revision (BIRDS)

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/biodiversity-portal#13]
- Check present default data access type in the last data call.

- Notify data submitters on B3 data delivered until now not flagged by any data access type

**Comment by neil-ices-dk** [comment]
We default to public for time being and with next data call invite data providers to update if they want to change the labels for B3 as they are now.

**Comment by neil-ices-dk** [comment]
@ospar-odims please note the above for your cover letter for the 2020 data call;

**Comment by neil-ices-dk** [comment]
> 
> 
> @ospar-odims please note the above for your cover letter for the 2020 data call;

@ospar-odims to consider this for guidance document and cover letter, related to #8
