### ISSUE TITLE
Make data Call for Birds?

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/biodiversity-portal#14]
Has there been agreed on frequency for data calls?
Has it been agreed on the dates for the next data call?

**Comment by neil-ices-dk** [comment]
@LenaAvellan to update after discussion at BDC end of Feb

**Comment by moultonc** [comment]
No conclusion from BDC on whether there would be a data call this year.

**Comment by neil-ices-dk** [comment]
from Chris/Lena 

A single data call will be issued to all Contracting Parties in November 2020. The data call will be almost identical to the one issued in 2016 prior to the IA2017.
The idea of a call in 2019 has been ditched; they were considering it before on a smaller set of species but that seems to have been dropped
