### ISSUE TITLE
Data call for birds

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/biodiversity-portal#21]
for the data call of birds we have a template we need to test, 

also it is important to:

1)	test the file with some data, we need to be sure that is working correctly and the more people it test the better.

2)	not to include the file in the datacall, instead include a link to the template in the data call (http://ices.dk/marine-data/Documents/biodiversity/OSPAR_Birds_Reporting_Format.xlsm)
The reason for this is that if there is any change (in field type or vocabs) then we can still correct it, while if you include it in the data call it won’t give us any change of correcting it.

**Comment by cmspinto** [comment]
[OSPAR_Birds_Reporting_Format - 2020-12-02.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5631546/OSPAR_Birds_Reporting_Format.-.2020-12-02.zip)

**Comment by cmspinto** [comment]
Hi, 

After a few tests this is the template that should be used: 
[OSPAR_Birds_Reporting_Format - 2020-12-03.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5634933/OSPAR_Birds_Reporting_Format.-.2020-12-03.zip)

**Comment by cmspinto** [comment]
@Osanna123  or @neil-ices-dk  to replace the template in the sharepoint

**Comment by Osanna123** [comment]
the template is updated on web
