### ISSUE TITLE
Finalize Seals data format

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/biodiversity-portal#4]
We got very close to finalizing the data format with Nora before she left her position, however we now need to pick this up and validate afresh before we can move forward with the seals part of the biodiversity database

**Comment by neil-ices-dk** [comment]
WGMME are meeting on the 19-22 February in France and could potentially review the format under their ToR on support for the 'seals database', _or not as it turns out they have an additional Database where they may have their focus_

**Comment by LenaAvellan** [comment]
BDC 2018 that is meeting 19-23 Feb will a) talk about updating frequencies b) data streams in general, noting further work being needed for the seals-data-format c) how to revive the OSPAR seal group. Under c), the experts have identified an important link to clarify as that to ICES mammals group, so important to know about the groups meeting and the fact that they have other databases, also as input to that discussion. 
From the OSPAR side, I think it will be only after BDC that we can return to the issue with expert engagement.

**Comment by neil-ices-dk** [comment]
@LenaAvellan to report back from BDC

**Comment by neil-ices-dk** [comment]
[Seal Data Reporting Format_20201109.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5523212/Seal.Data.Reporting.Format_20201109.docx)

[OSPAR_Seals_datacall_reporting format_v1 97_20201109_incomplete.xlsx](https://github.com/ices-tools-dev/biodiversity-portal/files/5523221/OSPAR_Seals_datacall_reporting.format_v1.97_20201109_incomplete.xlsx) (note have removed macro to include here)

**Comment by Osanna123** [comment]
Units are spatial; we need a description about relation between different units
Relationship model would be useful to understand how different records relate to each other (@anitagilles and @farahchaudry )
2 data tabs- Seal_AU_Totals and Haulout_Breeding_Unit_Abundance can be reported independently, at least the first one
Wadden Sea (3 countries) - one country can report on behalf of others
Data access needs to be cleared up (@ospar-odims , @neil-ices-dk )
Table 5 in doc needs to be a new tab in the template
Definitions of assessment units, reporting units for data submitters and then for data users (first vocab, then the exact definitions when they are finalized

**Comment by neil-ices-dk** [comment]
[Seal Data Reporting Format_20201126.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5604674/Seal.Data.Reporting.Format_20201126.docx)
revised version received from Farah

**Comment by neil-ices-dk** [comment]
@Osanna123 to look at the format (by 4th Dec)
@ospar-odims to review the data_access text in the format and make consistent with the bird format text - done in version dated 20201127 below
@farahchaudry to send version with track changes; add spatial scale - done in version dated 20201126 below

**Comment by farahchaudry** [comment]
[Seal Data Reporting Format_20201126.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5607365/Seal.Data.Reporting.Format_20201126.docx)
Revised version of data format - with tracked changes

**Comment by moultonc** [comment]
[Seal-Data-Reporting-Format_20201127.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5608128/Seal-Data-Reporting-Format_20201127.docx)
Revised version of data format - with tracked changes (edited data access text)
Version dated 20201126 deleted; Version 20201127 builds on this.

**Comment by farahchaudry** [comment]
[Seal-Data-Reporting-Format_20201204_tracked.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5642306/Seal-Data-Reporting-Format_20201204_tracked.docx)
Revised version of data format with tracked changes - following meeting on 4th Dec. Some of @Osanna123's requested changes have been included. Builds on Version 20201127.
This is the version sent to COBAM for approval on 4th Dec (with tracking and comments removed).

**Comment by moultonc** [comment]
@farahchaudry Following COBAM, I will draft data call text to complete the package so that we are prepared to issue the call early next year

**Comment by Osanna123** [comment]
latest draft format version for today's meeting
[OSPAR_Seals_reporting format_v2.1_20210121.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5848585/OSPAR_Seals_reporting.format_v2.1_20210121.zip)

**Comment by Osanna123** [comment]
[OSPAR_Seals_reporting format_v2.2_20210122.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5855433/OSPAR_Seals_reporting.format_v2.2_20210122.zip)
Latest format with changes agreed yesterday, and polished references. So far, i left all 3 area references, and we can check if something can be dropped for the next data call.
Pending issues:
Finalizing Assessment units
Approval of Contact in the File Information and PARAM with Value in the SealAUTotals and the Haulout/BreedingUnitAbundance records
Assigning codes for some Vocabularies - will take it with the Reference Governance Group on Wednesday

**Comment by farahchaudry** [comment]
[Seal-Data-Reporting-Format_20210122_tracked.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5857550/Seal-Data-Reporting-Format_20210122_tracked.docx)
@Osanna123 - latest version of guidance with tracked changes. This still needs amendments in relation to the Assessment Units.

**Comment by moultonc** [comment]
@Osanna123 @farahchaudry 
Finalised Assessment Units attached. Edited 28/01/2021 to include amendment between AU 22 and 23.

[OSPAR_Seals_AU.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5887583/OSPAR_Seals_AU.zip)
![Seals-AU](https://user-images.githubusercontent.com/8385739/105985618-98814600-6093-11eb-8b69-009a49be4e49.png)
