### ISSUE TITLE
Birds Format template edits as a part of preparation for the next data call

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/biodiversity-portal#8]
- Add field ‘SurveyID’ to the ‘Birds_site_description’
- Make ‘B1_Abundance_data’ optional, or make 2 separate submission forms for B1 and B3
- Add ‘Data_access’ field to the ‘B3_Breeding_success’

**Comment by neil-ices-dk** [comment]
> 
> 
>     * Add field ‘SurveyID’ to the ‘Birds_site_description’
> 
>     * Make ‘B1_Abundance_data’ optional, or make 2 separate submission forms for B1 and B3
> 
>     * Add ‘Data_access’ field to the ‘B3_Breeding_success’

@cmspinto and @Osanna123 to implement and inform ian

**Comment by neil-ices-dk** [comment]
@cmspinto to update XML and then we can send package to Ian;

@IanMitchell1 can you recall why we needed SurveyID in Birds_site_description?

**Comment by IanMitchell1** [comment]
> @cmspinto to update XML and then we can send package to Ian;
> 
> @IanMitchell1 can you recall why we needed SurveyID in Birds_site_description?

Probably because some sites had the same name but were in different surveys?

**Comment by neil-ices-dk** [comment]
**table 6**: anything related to baselines is changed to [optional]; Ian will change this in the guidance, @Osanna123 and @cmspinto to do this in the format/database

**Map**
@ospar-odims to provide updated birds map (shapefile); (figure A in the guidance)

@cmspinto  and @neil-ices-dk to dig up Word format guidance document;

@ospar-odims to add accessions@ices.dk to OSPAR data call mailing list

**Comment by cmspinto** [comment]
[OSPAR_B1_3_Reporting_Format_2015_Guidance_ICEScomments_IM.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5537804/OSPAR_B1_3_Reporting_Format_2015_Guidance_ICEScomments_IM.docx)

**Comment by moultonc** [comment]
[DRAFT_MSFD_AGDBIRD_SubRegions.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5537847/DRAFT_MSFD_AGDBIRD_SubRegions.zip)

**Comment by IanMitchell1** [comment]
> [DRAFT_MSFD_AGDBIRD_SubRegions.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5537847/DRAFT_MSFD_AGDBIRD_SubRegions.zip)

This is the earlier version. It needs updating and a new link inserting in the guidance

**Comment by IanMitchell1** [comment]
[Birds_Reporting_Format_QSR2023_Guidance_v1.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5539078/Birds_Reporting_Format_QSR2023_Guidance_v1.docx)

This is teh revised guidance. 

@Osanna123  and @cmspinto please check changes highlighted in yellow are also replicated in the XML file.

@ospar-odims chris can you please check references to Data access and add a link to teh new shapefile of assessment units to figure 1 caption

**Comment by moultonc** [comment]
> > [DRAFT_MSFD_AGDBIRD_SubRegions.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5537847/DRAFT_MSFD_AGDBIRD_SubRegions.zip)
> 
> This is the earlier version. It needs updating and a new link inserting in the guidance

@IanMitchell1 Let me know how it needs updating, this is the only file that we have from IA2017.

**Comment by moultonc** [comment]
> [Birds_Reporting_Format_QSR2023_Guidance_v1.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5539078/Birds_Reporting_Format_QSR2023_Guidance_v1.docx)
> 
> This is teh revised guidance.
> 
> @Osanna123 and @cmspinto please check changes highlighted in yellow are also replicated in the XML file.
> 
> @ospar-odims chris can you please check references to Data access and add a link to teh new shapefile of assessment units to figure 1 caption

I'll check this and use it as a basis to draft the data call document

**Comment by moultonc** [comment]
@IanMitchell1 The data call is attached and revisions to the guidance doc based on some of Lena's comments.
[OSPAR_B1-B3-data_call_20201117.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5554369/OSPAR_B1-B3-data_call_20201117.docx)
[Birds_Reporting_Format_QSR2023_Guidance_v1.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5554371/Birds_Reporting_Format_QSR2023_Guidance_v1.docx)

**Comment by IanMitchell1** [comment]
@ospar-odims  Chris - thanks for the datacall. I'm happy with lena's text changes to the guidance. Did you check the text on ospar data restrictions and could you please provide a link to the shapefile for the assessment units in fig 2?

@Osanna123  & @cmspinto have you updated the XML? Do you have an online link to it that we can include in the datacall?

Once we have sorted the above, we can issue the datacall

**Comment by ospar-odims** [comment]
@IanMitchell1 Updated data call with included link and data conditions, attached
[Birds_Reporting_Format_QSR2023_Guidance_v1.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5603168/Birds_Reporting_Format_QSR2023_Guidance_v1.docx)

**Comment by moultonc** [comment]
@IanMitchell1 Revised data call and reporting format attached.
[OSPAR_B1-B3-data_call_20201126.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5603212/OSPAR_B1-B3-data_call_20201126.docx)
[Birds_Reporting_Format_QSR2023_Guidance_v1.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5603213/Birds_Reporting_Format_QSR2023_Guidance_v1.docx)

**Comment by neil-ices-dk** [comment]
JPEG of AU's in Kattegat is a little off; @ospar-odims to make an amendment to the polygon and extract a new jpeg (27/11);
@IanMitchell1 to upload final versions of data call and guidance (27/11);
@Osanna123 and to make a final review of template and guidance to make sure they are coherent i.e. SiteID (by 30/11) ;
@cmspinto to update template/XML (by 30/11)

**Comment by IanMitchell1** [comment]
[OSPAR_B1-B3-data_call_FINAL.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5607159/OSPAR_B1-B3-data_call_FINAL.docx)
[Birds_Reporting_Format_QSR2023_Guidance_FINAL.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5607160/Birds_Reporting_Format_QSR2023_Guidance_FINAL.docx)

@ospar-odims  to update map and resubmission text
@cmspinto to check new fields (highlighted in yellow in guidance doc) have been added to XML

**Comment by moultonc** [comment]
> @ospar-odims to update map and resubmission text

[OSPAR_B1-B3-data_call.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5608055/OSPAR_B1-B3-data_call.docx)
[Birds_Reporting_Format_QSR2023_Guidance.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5608056/Birds_Reporting_Format_QSR2023_Guidance.docx)
@IanMitchell1: Map updated, ODIMS updated with revised assessment units [extra bit added into the Kattegat], updated data access guidance to reflect the updated data policy box [removal of the "OSPAR" option and refinement of "Public" text to remove OSPAR reference] and a small paragraph added to the intro box regarding resubmission, in tracked changes. Please tweak or accept and then I will schedule it to be sent out.

**Comment by IanMitchell1** [comment]
> > @ospar-odims to update map and resubmission text
> 
> [OSPAR_B1-B3-data_call.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5608055/OSPAR_B1-B3-data_call.docx)
> [Birds_Reporting_Format_QSR2023_Guidance.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5608056/Birds_Reporting_Format_QSR2023_Guidance.docx)
> @IanMitchell1: Map updated, ODIMS updated with revised assessment units [extra bit added into the Kattegat], updated data access guidance to reflect the updated data policy box [removal of the "OSPAR" option and refinement of "Public" text to remove OSPAR reference] and a small paragraph added to the intro box regarding resubmission, in tracked changes. Please tweak or accept and then I will schedule it to be sent out.

Thanks Chris  - over to you @carlos

**Comment by Osanna123** [comment]
New data submission template is published

**Comment by IanMitchell1** [comment]
[OSPAR_B1-B3-data_call_2020_03_12.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5643290/OSPAR_B1-B3-data_call_2020_03_12.docx)
[Birds_Reporting_Format_QSR2023_Guidance_2020_03_12.docx](https://github.com/ices-tools-dev/biodiversity-portal/files/5643291/Birds_Reporting_Format_QSR2023_Guidance_2020_03_12.docx)

These are the final final versions of the datacall and guidance that I have asked @ospar-odims  to circulate. Please could @cmspinto or @Osanna123 upload them to the ices biodiversity portal. I have  taken onboard @Osanna123 comments and checked all the links.  We  will not circulate the xml as requested by @cmspinto

**Comment by Osanna123** [comment]
@IanMitchell1 , thanks for the new version of the Guidance doc, we'll publish it online. Normally, we do not publish the data call file on our web, but we could include a link to the call on OSPAR web...
Carlos and i have a question though - do you remember why the Baselines and Weightings are not a part of the submission format, but are managed entirely separately?
